openapi: 3.0.1
info:
  title: unicorn-api-shipping-v1
  description: Unicorn Coffee API for Shipping
  version: 0.1.0

components:
  securitySchemes:
    unicorn-api-authorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        authorizerResultTtlInSeconds: 10
        authorizerUri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${apiAuthorizer}/invocations'
        identitySource: method.request.header.Authorization
        type: request

paths:
  /:
    get:
      summary: shipping
      description: returns list of shipments
      responses:
        200:
          description: ok
        default:
          description: error
      security:
        - unicorn-api-authorizer: []
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion:
          Fn::Sub: '${payloadVersion}'
        responses:
          default:
            statusCode: 200
        type: AWS_PROXY
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Fn.Arn}/invocations'
    post:
      summary: shipping
      description: create shipment
      responses:
        200:
          description: ok
        default:
          description: error
      security:
        - unicorn-api-authorizer: []
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion:
          Fn::Sub: '${payloadVersion}'
        responses:
          default:
            statusCode: 200
        type: AWS_PROXY
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Fn.Arn}/invocations'
