openapi: 3.0.1
info:
  title: apigw-api-keys
  description: Testing API keys
  version: 0.1.0

components:
  securitySchemes:
    api-key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"

paths:
  /test:
    get:
      summary: test
      description: returns test
      responses:
        200:
          description: ok
      security:
      - api-key: []
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion:
          Fn::Sub: '${payloadVersion}'
        type: aws_proxy
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Fn.Arn}/invocations'
    post:
      summary: test
      description: create test
      responses:
        200:
          description: ok
      security:
      - api-key: []
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion:
          Fn::Sub: '${payloadVersion}'
        type: aws_proxy
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Fn.Arn}/invocations'
