AWSTemplateFormatVersion: '2010-09-09'
Description: Unicorn Coffee APIGW custom domain name
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    OpenApiVersion: 3.0.1
Parameters:
  certificateArn:
    Type: String
  domainName:
    Type: String
  hostedZoneId:
    Type: String
Resources:
  ApiDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref domainName
      DomainNameConfigurations:
        - CertificateArn: !Ref certificateArn
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2
  ApiDomainRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref hostedZoneId
      Name: !Ref domainName
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt ApiDomain.RegionalHostedZoneId
        DNSName: !GetAtt ApiDomain.RegionalDomainName
Outputs:
  apiDomain:
    Value: !Ref ApiDomain
  apiDomainRecordSet:
    Value: !Ref ApiDomainRecordSet
