AWSTemplateFormatVersion: '2010-09-09'
Description: Unicorn Coffee Processor
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.8
    Timeout: 60
Resources:
  # S3
  Bucket:
    Type: AWS::S3::Bucket
  # Lambda
  FnExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/service-role/'
      Policies:
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:log-group:*:*'
  # FnLabels
  FnLabels:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: fn_labels.handler
      Role: !GetAtt FnExecRole.Arn
      Events:
        ObjectCreatedEvent:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
  FnLabelsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FnLabels}"
      RetentionInDays: 7

