openapi: 3.0.1
info:
  title: unicorn-api-processor
  description: Unicorn Coffee API for Processing Usage
  version: 0.1.0

components:
  securitySchemes:
    unicorn-api-authorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        authorizerUri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${apiAuthorizer}/invocations'
        authorizerPayloadFormatVersion:
          Fn::Sub: '${payloadVersion}'
        authorizerResultTtlInSeconds: 2
        enableSimpleResponses:
          Fn::Sub: '${enableSimple}'
        identitySource: $request.header.Authorization
        type: request

paths:
  /landing:
    get:
      summary: landing
      description: returns presigned url for uploading image
      responses:
        200:
          description: ok
        default:
          description: error
      security:
        - unicorn-api-authorizer: []
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion:
          Fn::Sub: '${payloadVersion}'
        responses:
          default:
            statusCode: 200
        type: AWS_PROXY
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FnLanding.Arn}/invocations'
  /usage:
    post:
      summary: usage
      description: gets usage information
      responses:
        200:
          description: ok
        default:
          description: error
      security:
        - unicorn-api-authorizer: []
      x-amazon-apigateway-integration:
        httpMethod: POST
        payloadFormatVersion:
          Fn::Sub: '${payloadVersion}'
        responses:
          default:
            statusCode: 200
        type: AWS_PROXY
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FnUsage.Arn}/invocations'
  /label:
    post:
      summary: label
      description: gets image labels
      responses:
        200:
          description: ok
        default:
          description: error
      # security:
      #   - unicorn-api-authorizer: []
      x-amazon-apigateway-integration:
        integrationSubtype: StepFunctions-StartExecution
        credentials:
          Fn::Sub: '${ApiExecRole.Arn}'
        requestParameters:
          Input: $request.body
          StateMachineArn:
            Fn::Sub: 'arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${sf}'
        payloadFormatVersion: 1.0
        type: AWS_PROXY
        connectionType: INTERNET